### ISSUE TITLE
Broken in Python 2

### ISSUE THREAD

**Issue by tchamberlin** [tchamberlin/collatelogs#1]
```
$ collatelogs
Traceback (most recent call last):
  File "/home/sandboxes/tchamber/venvs/twc_python2/bin/collatelogs", line 3, in <module>
    from collatelogs import __main__
  File "/home/sandboxes/tchamber/venvs/twc_python2/lib/python2.7/site-packages/collatelogs/__main__.py", line 1, in <module>
    from collatelogs import cli
  File "/home/sandboxes/tchamber/venvs/twc_python2/lib/python2.7/site-packages/collatelogs/collatelogs.py", line 25, in <module>
    from collatelogs import cli
ImportError: cannot import name cli
```

Works fine in Python 3, but I must have broken Python 2 when refactoring things at the end.

**Comment by tchamberlin** [comment]
Fixed by  b391527
